---
- name: show_command
  hosts: junos_devices
  roles:
    - Juniper.junos
  gather_facts: no
  
  vars:
    facts_dir: "/mnt/c/Users/LAP15255-local/Desktop/python/Ansible/test"
    systime: "{{ ansible_date_time.time | replace(':','.') }}"
    timestamp: "{{ ansible_date_time.date }}_{{ systime }}"
  tasks:
    - name: setup 
      setup:
        gather_subset:
          - 'min'

    # - name: confirm/create report directory
    #   file:
    #     path: "{{ facts_dir }}"
    #     state: directory
    #   run_once: yes
    #   delegate_to: localhost

    - name: Info port down/up
      junos_command:
        commands: show interfaces terse
      register: junos_port_down_up

    - name: Info port description
      junos_command:
        commands: show interfaces descriptions
      register: junos_port_description

    - name: Info port 
      junos_command:
        commands:
        - "show interfaces terse" 
        - "show interfaces descriptions"
      register: junos_info_port
    
    
    # - name: check if Physical Interface are UP
    #   junipernetworks.junos.junos_command:
    #     commands:
    #       - "show interfaces terse {{ item.interface }}"
    #     display: "xml"
    #     # wait_for: result[0] contains up
    
    - name: show info port down up
      debug:
        var: junos_port_down_up.stdout_lines
    - name: show info port
      debug:
        var: junos_info_port.stdout_lines
    
    - name: copy show info port
      copy:
        content: "{{ junos_info_port.stdout_lines }}"
        dest: ./test/info_port_{{ timestamp }}.text