---
- name: show_command
  hosts: junos_devices
  roles:
    - Juniper.junos
  gather_facts: no
  
  vars:
    facts_dir: "/mnt/c/Users/LAP15255-local/Desktop/python/Ansible/test"
    systime: "{{ ansible_date_time.time | replace(':','.') }}"
    timestamp: "{{ ansible_date_time.date }}_{{ systime }}"
  tasks:
    - name: setup 
      setup:
        gather_subset:
          - 'min'

    - name: confirm/create report directory
      file:
        path: "{{ facts_dir }}"
        state: directory
      run_once: yes
      delegate_to: localhost


    - name: Info port description
      junos_command:
        commands: show interfaces descriptions
      register: junos_port_description

    - name: show info port
      debug:
        msg: "{{ junos_port_description.stdout_lines }}"

    - name: copy show info port
      copy:
        content: "{{ junos_port_description.stdout_lines }}"
        dest: ./test/info_port_{{ timestamp }}

    - name: send e-mail
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: thanhebooks@gmail.com
        password: mrik aygo qsmu wzqr
        to: vominhthanh.lop94@gmail.com
        subject: Ansible-report
        subtype: html
        attach: /home/vsu/semaphone-lab/test/info_port_{{ timestamp }}
        body:
        - 'System {{ ansible_hostname }} has been successfully provisioned.'
        - "{{ lookup ('file', '/home/vsu/semaphone-lab/test/info_port_{{ timestamp }}') }}"
      delegate_to: localhost

